apiVersion: neuvector.com/v1
kind: NvConfigSecurityRule
metadata:
  creationTimestamp: null
  name: fed
spec:
  fed_config:
    name: fed
    webhooks:
    - enable: true
      name: fed.wh1
      type: ""
      url: https://test123.com
      use_proxy: false
    - enable: true
      name: fed.wh2
      type: Teams
      url: https://aaa123.com
      use_proxy: false
