apiVersion: neuvector.com/v1
kind: NvConfigSecurityRule
metadata:
  creationTimestamp: null
  name: fed
spec:
  fed_config:
    name: fed
    webhooks:
    - enable: true
      name: fed.wb1
      type: ""
      url: https://test123.com
      use_proxy: true
