apiVersion: neuvector.com/v1
kind: NvConfigSecurityRule
metadata:
  creationTimestamp: null
  name: fed
spec:
  fed_config:
    name: fed
    webhooks:
    - enable: true
      name: fed.test1
      type: JSON
      url: https://test123.com
      use_proxy: false
    - enable: true
      name: fed.test2
      type: ""
      url: https://test1234.com
      use_proxy: false
